// Writes a Swift file that carries source files as base64 strings.
//
//   apvt-embed <output.swift> <group>=<path> …
//
// Used by the EmbedAgentSources plugin so the `apvt` binary carries the agent's sources and can
// build the agent for the simulator on a machine that only has the binary.

import Foundation

let arguments = CommandLine.arguments.dropFirst()
guard let output = arguments.first else {
    FileHandle.standardError.write(Data("usage: apvt-embed <output.swift> <group>=<path> …\n".utf8))
    exit(2)
}

var entries: [String] = []
for spec in arguments.dropFirst().sorted() {
    guard let eq = spec.firstIndex(of: "=") else { continue }
    let group = String(spec[..<eq])
    let path = String(spec[spec.index(after: eq)...])
    let data = try Data(contentsOf: URL(fileURLWithPath: path))
    let name = URL(fileURLWithPath: path).lastPathComponent
    entries.append("        EmbeddedSource(group: \"\(group)\", name: \"\(name)\", base64: \"\(data.base64EncodedString())\"),")
}

let source = """
// Generated by apvt-embed. Do not edit.

struct EmbeddedSource: Sendable {
    let group: String
    let name: String
    let base64: String
}

enum EmbeddedAgentSources {
    static let files: [EmbeddedSource] = [
\(entries.joined(separator: "\n"))
    ]
}

"""
try source.write(toFile: output, atomically: true, encoding: .utf8)
